config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :artists do
    resources :songs, except: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :songs, dependent: :destroy
  validates :name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      image_params.each do |image|
        @artist.image.create(image: image)
      end

      redirect_to edit_artist_path(@artist), notice: "Artist added"
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
    image_params.each do |image|
      @artist.image.create(image: image)
    end

      redirect_to edit_artist_path(@artist), notice: "Artist updated"
    else
      render :edit
    end
  end

  private

  def image_params
    params[:image].present? ? params.require(:image) : []
  end

  def artist_params
    params.require(:artist).permit(:name, :remote_image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
  end

  def show
    @songs = songs
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :length)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>

  <div class="form-group">
    <label>Artist name</label>
    <%= f.text_area :name, placeholder: "Name of the artist", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Photo</label>
    <span class="btn btn-default">
      Upload photo
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", artist_path, class: "btn btn-default" %>
  </div>

<% end %>

app/views/artists/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit artist
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/index.html.erb
<h1>Artist Overview</h1>

<!-- Thumbnails -->
<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag artist.image.thumbnail %>
        <div class="caption">
          <h3>
            <%= link_to artist.name, artist_path(artist), class: "artist-name" %>
          </h3>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/artists/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add new artist and songs
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/artists/show.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4><%= @artist.name %> - List of songs</h4>
      </div>

      <div class="panel-body">
          <div class="row">
            <div class="col-md-7">
              <% if @artist.songs.any? %>
                <ul class="song-list">
                  <% @artist.songs.each do |song| %>
                    <li class="song-list-item"><%= song.title %></li>
                  <% end %>
                </ul>
              <% else %>
                <p>Whoops, there are no songs for this artist. Add some, if you like..</p>
              <% end %>
            </div>

            <div class="col-md-3 right">
              <%= link_to "Add new artist", new_artist_path, class: "btn btn-primary" %>
              <%= link_to "Edit List of songs", edit_artist_path(@artist), class: "btn btn-default" %>
            </div>
          </div>

      </div>
    </div>

    <%= link_to "Add new song", new_artist_song_path, class: "btn btn-primary" %>
    <%= link_to "Back to overview", artists_path, class: "btn btn-default" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400,600,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container hero">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="cover-container">

  <!-- Intro -->
  <div class="inner cover">
    <h1 class="cover-heading">Codaisseurify.</h1>
    <p class="lead">Build your personal music collection.<br>Add and update your favorite artists and their songs.</p>
    <p class="lead">
      <a href="artists/" class="btn btn-lg btn-primary">View Artists</a>
    </p>
  </div>
</div>

app/views/shared/_footer.html.erb
  <div class="mastfoot">
    <div class="inner">
      <p><a href="#">Codaisseurify</a> - The No1 App for Music Lovers</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for @songs do |f| %>

  <div class="form-group">
    <label>Song title</label>
    <%= f.text_area :name, placeholder: "Title of the song", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", artist_path, class: "btn btn-default" %>
  </div>

<% end %>